[package]
name = "grafeia_gui"
description = "γραφείο – gui"
version = "0.1.0"
authors = ["Sebastian K <s3bk@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grafeia_core = { path = "../core" }
pathfinder_content = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_geometry = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_gl = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_gpu = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_renderer = { git = "https://github.com/s3bk/pathfinder/" }

font = { git = "https://github.com/pdf-rs/font" }

euclid = "0.19"
log = "0.4.8"
env_logger = "*"
gl = "0.6"
sdl2 = "0.32"
sdl2-sys = "0.32"
glutin = { git = "https://github.com/rust-windowing/glutin/" }
winit = { git = "https://github.com/rust-windowing/winit/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
